config/routes.rb
Rails.application.routes.draw do
  resources :targets

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  ## Relations
  belongs_to :target

  ## Etc.
  mount_uploader :file, FileUploader
end

app/models/target.rb
class Target < ActiveRecord::Base
  ## Relations
  has_many :photos

  ## Variables
  GENDER = %w(male female)

  ## Validates
  validates :gender, inclusion: { in: GENDER }
  validates :name, :dob, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :set_target, only: [:show, :edit, :update, :destroy]

  # GET /targets
  # GET /targets.json
  def index
    @targets = Target.all
  end

  # GET /targets/1
  # GET /targets/1.json
  def show
  end

  # GET /targets/new
  def new
    @target = Target.new
  end

  # GET /targets/1/edit
  def edit
  end

  # POST /targets
  # POST /targets.json
  def create
    @target = Target.new(target_params)

    respond_to do |format|
      if @target.save
        format.html { redirect_to @target, notice: 'Target was successfully created.' }
        format.json { render :show, status: :created, location: @target }
      else
        format.html { render :new }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /targets/1
  # PATCH/PUT /targets/1.json
  def update
    respond_to do |format|
      if @target.update(target_params)
        format.html { redirect_to @target, notice: 'Target was successfully updated.' }
        format.json { render :show, status: :ok, location: @target }
      else
        format.html { render :edit }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1
  # DELETE /targets/1.json
  def destroy
    @target.destroy
    respond_to do |format|
      format.html { redirect_to targets_url, notice: 'Target was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_target
      @target = Target.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def target_params
      params.require(:target).permit(:name, :gender, :dob)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def content_class
    controller_name + ' ' + action_name 
  end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Age18</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= content_class %>">

<%= yield %>

</body>
</html>

app/views/targets/_form.html.erb
<%= form_for(@target, html: {class: 'frontend formSubmitLoaderJS'}) do |f| %>
  <% if @target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@target.errors.count, "error") %> prohibited this target from being saved:</h2>

      <ul>
      <% @target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field dob">
    <%= f.label :dob %>
    <%= f.text_field :dob, :databehaviour=>"datepicker", :placeholder=>"01.01.1980" %>
  </div>

  <div class="field gender">
    <%= f.label :gender %>

    <%= content_tag :div, class: 'female' do %>
      <%= f.radio_button :gender, :female, class: 'hidden' %>
      <%= f.label :gender_female %>
    <% end %>

    <%= content_tag :div, class: 'male' do %>
      <%= f.radio_button :gender, :male, class: 'hidden' %>
      <%= f.label :gender_male %>
    <% end %>
  </div>

  <%= content_tag :div, class: 'targetSubmitWrap' do %>
    <%= f.submit %>
    <%= content_tag :div, class: 'targetButton button customFormButtonJS hidden' do %>
      <%= content_tag :span, t('.make') %>
    <% end %>
  <% end %>
<% end %>

app/views/targets/edit.html.erb
<h1>Editing target</h1>

<%= render 'form' %>

<%= link_to 'Show', @target %> |
<%= link_to 'Back', targets_path %>

app/views/targets/index.html.erb
<h1>Listing targets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Contacts</th>
      <th>Dob</th>
      <th>Alert age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @targets.each do |target| %>
      <tr>
        <td><%= target.name %></td>
        <td><%= target.gender %></td>
        <td><%= target.contacts %></td>
        <td><%= target.dob %></td>
        <td><%= target.alert_age %></td>
        <td><%= link_to 'Show', target %></td>
        <td><%= link_to 'Edit', edit_target_path(target) %></td>
        <td><%= link_to 'Destroy', target, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Target', new_target_path %>

app/views/targets/new.html.erb
<%= content_tag :div, class: 'form_box' do %>
  <%= content_tag :h1, t('.new_target') %>
  <%= render 'form' %>
<% end %>

app/views/targets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @target.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @target.gender %>
</p>

<p>
  <strong>Contacts:</strong>
  <%= @target.contacts %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @target.dob %>
</p>

<p>
  <strong>Alert age:</strong>
  <%= @target.alert_age %>
</p>

<%= link_to 'Edit', edit_target_path(@target) %> |
<%= link_to 'Back', targets_path %>